/* File generated by the BNF Converter (bnfc 2.9.4). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"



void Skeleton::visitProgram(Program *t) {} //abstract class
void Skeleton::visitTopDef(TopDef *t) {} //abstract class
void Skeleton::visitArg(Arg *t) {} //abstract class
void Skeleton::visitBlock(Block *t) {} //abstract class
void Skeleton::visitClassBlock(ClassBlock *t) {} //abstract class
void Skeleton::visitClassStmt(ClassStmt *t) {} //abstract class
void Skeleton::visitStmt(Stmt *t) {} //abstract class
void Skeleton::visitItem(Item *t) {} //abstract class
void Skeleton::visitExtIdent(ExtIdent *t) {} //abstract class
void Skeleton::visitPrimType(PrimType *t) {} //abstract class
void Skeleton::visitType(Type *t) {} //abstract class
void Skeleton::visitExpr(Expr *t) {} //abstract class
void Skeleton::visitAddOp(AddOp *t) {} //abstract class
void Skeleton::visitMulOp(MulOp *t) {} //abstract class
void Skeleton::visitRelOp(RelOp *t) {} //abstract class

void Skeleton::visitProg(Prog *prog)
{
  /* Code For Prog Goes Here */

  if (prog->listtopdef_) prog->listtopdef_->accept(this);

}

void Skeleton::visitFnDef(FnDef *fn_def)
{
  /* Code For FnDef Goes Here */

  if (fn_def->type_) fn_def->type_->accept(this);
  visitIdent(fn_def->ident_);
  if (fn_def->listarg_) fn_def->listarg_->accept(this);
  if (fn_def->block_) fn_def->block_->accept(this);

}

void Skeleton::visitClassDef(ClassDef *class_def)
{
  /* Code For ClassDef Goes Here */

  visitIdent(class_def->ident_);
  if (class_def->classblock_) class_def->classblock_->accept(this);

}

void Skeleton::visitExtClassDef(ExtClassDef *ext_class_def)
{
  /* Code For ExtClassDef Goes Here */

  visitIdent(ext_class_def->ident_1);
  visitIdent(ext_class_def->ident_2);
  if (ext_class_def->classblock_) ext_class_def->classblock_->accept(this);

}

void Skeleton::visitAr(Ar *ar)
{
  /* Code For Ar Goes Here */

  if (ar->type_) ar->type_->accept(this);
  visitIdent(ar->ident_);

}

void Skeleton::visitBloc(Bloc *bloc)
{
  /* Code For Bloc Goes Here */

  if (bloc->liststmt_) bloc->liststmt_->accept(this);

}

void Skeleton::visitClassBloc(ClassBloc *class_bloc)
{
  /* Code For ClassBloc Goes Here */

  if (class_bloc->listclassstmt_) class_bloc->listclassstmt_->accept(this);

}

void Skeleton::visitClassEmpty(ClassEmpty *class_empty)
{
  /* Code For ClassEmpty Goes Here */


}

void Skeleton::visitClassDecl(ClassDecl *class_decl)
{
  /* Code For ClassDecl Goes Here */

  if (class_decl->type_) class_decl->type_->accept(this);
  if (class_decl->listitem_) class_decl->listitem_->accept(this);

}

void Skeleton::visitClassMethod(ClassMethod *class_method)
{
  /* Code For ClassMethod Goes Here */

  if (class_method->type_) class_method->type_->accept(this);
  visitIdent(class_method->ident_);
  if (class_method->listarg_) class_method->listarg_->accept(this);
  if (class_method->block_) class_method->block_->accept(this);

}

void Skeleton::visitEmpty(Empty *empty)
{
  /* Code For Empty Goes Here */


}

void Skeleton::visitBStmt(BStmt *b_stmt)
{
  /* Code For BStmt Goes Here */

  if (b_stmt->block_) b_stmt->block_->accept(this);

}

void Skeleton::visitDecl(Decl *decl)
{
  /* Code For Decl Goes Here */

  if (decl->type_) decl->type_->accept(this);
  if (decl->listitem_) decl->listitem_->accept(this);

}

void Skeleton::visitAss(Ass *ass)
{
  /* Code For Ass Goes Here */

  if (ass->extident_) ass->extident_->accept(this);
  if (ass->expr_) ass->expr_->accept(this);

}

void Skeleton::visitIncr(Incr *incr)
{
  /* Code For Incr Goes Here */

  if (incr->extident_) incr->extident_->accept(this);

}

void Skeleton::visitDecr(Decr *decr)
{
  /* Code For Decr Goes Here */

  if (decr->extident_) decr->extident_->accept(this);

}

void Skeleton::visitRet(Ret *ret)
{
  /* Code For Ret Goes Here */

  if (ret->expr_) ret->expr_->accept(this);

}

void Skeleton::visitVRet(VRet *v_ret)
{
  /* Code For VRet Goes Here */


}

void Skeleton::visitCond(Cond *cond)
{
  /* Code For Cond Goes Here */

  if (cond->expr_) cond->expr_->accept(this);
  if (cond->stmt_) cond->stmt_->accept(this);

}

void Skeleton::visitCondElse(CondElse *cond_else)
{
  /* Code For CondElse Goes Here */

  if (cond_else->expr_) cond_else->expr_->accept(this);
  if (cond_else->stmt_1) cond_else->stmt_1->accept(this);
  if (cond_else->stmt_2) cond_else->stmt_2->accept(this);

}

void Skeleton::visitWhile(While *while_)
{
  /* Code For While Goes Here */

  if (while_->expr_) while_->expr_->accept(this);
  if (while_->stmt_) while_->stmt_->accept(this);

}

void Skeleton::visitFor(For *for_)
{
  /* Code For For Goes Here */

  if (for_->type_) for_->type_->accept(this);
  visitIdent(for_->ident_);
  if (for_->extident_) for_->extident_->accept(this);
  if (for_->stmt_) for_->stmt_->accept(this);

}

void Skeleton::visitSExp(SExp *s_exp)
{
  /* Code For SExp Goes Here */

  if (s_exp->expr_) s_exp->expr_->accept(this);

}

void Skeleton::visitNoInit(NoInit *no_init)
{
  /* Code For NoInit Goes Here */

  visitIdent(no_init->ident_);

}

void Skeleton::visitInit(Init *init)
{
  /* Code For Init Goes Here */

  visitIdent(init->ident_);
  if (init->expr_) init->expr_->accept(this);

}

void Skeleton::visitId(Id *id)
{
  /* Code For Id Goes Here */

  visitIdent(id->ident_);

}

void Skeleton::visitArrId(ArrId *arr_id)
{
  /* Code For ArrId Goes Here */

  visitIdent(arr_id->ident_);
  if (arr_id->expr_) arr_id->expr_->accept(this);

}

void Skeleton::visitAttrId(AttrId *attr_id)
{
  /* Code For AttrId Goes Here */

  if (attr_id->expr_1) attr_id->expr_1->accept(this);
  if (attr_id->expr_2) attr_id->expr_2->accept(this);

}

void Skeleton::visitInt(Int *int_)
{
  /* Code For Int Goes Here */


}

void Skeleton::visitStr(Str *str)
{
  /* Code For Str Goes Here */


}

void Skeleton::visitBool(Bool *bool_)
{
  /* Code For Bool Goes Here */


}

void Skeleton::visitVoid(Void *void_)
{
  /* Code For Void Goes Here */


}

void Skeleton::visitPrimitive(Primitive *primitive)
{
  /* Code For Primitive Goes Here */

  if (primitive->primtype_) primitive->primtype_->accept(this);

}

void Skeleton::visitObjectType(ObjectType *object_type)
{
  /* Code For ObjectType Goes Here */

  visitIdent(object_type->ident_);

}

void Skeleton::visitArray(Array *array)
{
  /* Code For Array Goes Here */

  if (array->type_) array->type_->accept(this);

}

void Skeleton::visitFun(Fun *fun)
{
  /* Code For Fun Goes Here */

  if (fun->type_) fun->type_->accept(this);
  if (fun->listtype_) fun->listtype_->accept(this);

}

void Skeleton::visitECast(ECast *e_cast)
{
  /* Code For ECast Goes Here */

  visitIdent(e_cast->ident_);
  if (e_cast->expr_) e_cast->expr_->accept(this);

}

void Skeleton::visitECastPrim(ECastPrim *e_cast_prim)
{
  /* Code For ECastPrim Goes Here */

  if (e_cast_prim->primtype_) e_cast_prim->primtype_->accept(this);
  if (e_cast_prim->expr_) e_cast_prim->expr_->accept(this);

}

void Skeleton::visitENewObject(ENewObject *e_new_object)
{
  /* Code For ENewObject Goes Here */

  visitIdent(e_new_object->ident_);

}

void Skeleton::visitENewArr(ENewArr *e_new_arr)
{
  /* Code For ENewArr Goes Here */

  if (e_new_arr->type_) e_new_arr->type_->accept(this);
  if (e_new_arr->expr_) e_new_arr->expr_->accept(this);

}

void Skeleton::visitENull(ENull *e_null)
{
  /* Code For ENull Goes Here */


}

void Skeleton::visitEObject(EObject *e_object)
{
  /* Code For EObject Goes Here */

  if (e_object->expr_1) e_object->expr_1->accept(this);
  if (e_object->expr_2) e_object->expr_2->accept(this);

}

void Skeleton::visitEArr(EArr *e_arr)
{
  /* Code For EArr Goes Here */

  visitIdent(e_arr->ident_);
  if (e_arr->expr_) e_arr->expr_->accept(this);

}

void Skeleton::visitEVar(EVar *e_var)
{
  /* Code For EVar Goes Here */

  visitIdent(e_var->ident_);

}

void Skeleton::visitELitInt(ELitInt *e_lit_int)
{
  /* Code For ELitInt Goes Here */

  visitInteger(e_lit_int->integer_);

}

void Skeleton::visitELitTrue(ELitTrue *e_lit_true)
{
  /* Code For ELitTrue Goes Here */


}

void Skeleton::visitELitFalse(ELitFalse *e_lit_false)
{
  /* Code For ELitFalse Goes Here */


}

void Skeleton::visitEApp(EApp *e_app)
{
  /* Code For EApp Goes Here */

  visitIdent(e_app->ident_);
  if (e_app->listexpr_) e_app->listexpr_->accept(this);

}

void Skeleton::visitEString(EString *e_string)
{
  /* Code For EString Goes Here */

  visitString(e_string->string_);

}

void Skeleton::visitNeg(Neg *neg)
{
  /* Code For Neg Goes Here */

  if (neg->expr_) neg->expr_->accept(this);

}

void Skeleton::visitNot(Not *not_)
{
  /* Code For Not Goes Here */

  if (not_->expr_) not_->expr_->accept(this);

}

void Skeleton::visitEMul(EMul *e_mul)
{
  /* Code For EMul Goes Here */

  if (e_mul->expr_1) e_mul->expr_1->accept(this);
  if (e_mul->mulop_) e_mul->mulop_->accept(this);
  if (e_mul->expr_2) e_mul->expr_2->accept(this);

}

void Skeleton::visitEAdd(EAdd *e_add)
{
  /* Code For EAdd Goes Here */

  if (e_add->expr_1) e_add->expr_1->accept(this);
  if (e_add->addop_) e_add->addop_->accept(this);
  if (e_add->expr_2) e_add->expr_2->accept(this);

}

void Skeleton::visitERel(ERel *e_rel)
{
  /* Code For ERel Goes Here */

  if (e_rel->expr_1) e_rel->expr_1->accept(this);
  if (e_rel->relop_) e_rel->relop_->accept(this);
  if (e_rel->expr_2) e_rel->expr_2->accept(this);

}

void Skeleton::visitEAnd(EAnd *e_and)
{
  /* Code For EAnd Goes Here */

  if (e_and->expr_1) e_and->expr_1->accept(this);
  if (e_and->expr_2) e_and->expr_2->accept(this);

}

void Skeleton::visitEOr(EOr *e_or)
{
  /* Code For EOr Goes Here */

  if (e_or->expr_1) e_or->expr_1->accept(this);
  if (e_or->expr_2) e_or->expr_2->accept(this);

}

void Skeleton::visitPlus(Plus *plus)
{
  /* Code For Plus Goes Here */


}

void Skeleton::visitMinus(Minus *minus)
{
  /* Code For Minus Goes Here */


}

void Skeleton::visitTimes(Times *times)
{
  /* Code For Times Goes Here */


}

void Skeleton::visitDiv(Div *div)
{
  /* Code For Div Goes Here */


}

void Skeleton::visitMod(Mod *mod)
{
  /* Code For Mod Goes Here */


}

void Skeleton::visitLTH(LTH *lth)
{
  /* Code For LTH Goes Here */


}

void Skeleton::visitLE(LE *le)
{
  /* Code For LE Goes Here */


}

void Skeleton::visitGTH(GTH *gth)
{
  /* Code For GTH Goes Here */


}

void Skeleton::visitGE(GE *ge)
{
  /* Code For GE Goes Here */


}

void Skeleton::visitEQU(EQU *equ)
{
  /* Code For EQU Goes Here */


}

void Skeleton::visitNE(NE *ne)
{
  /* Code For NE Goes Here */


}


void Skeleton::visitListTopDef(ListTopDef *list_top_def)
{
  for (ListTopDef::iterator i = list_top_def->begin() ; i != list_top_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListArg(ListArg *list_arg)
{
  for (ListArg::iterator i = list_arg->begin() ; i != list_arg->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListClassStmt(ListClassStmt *list_class_stmt)
{
  for (ListClassStmt::iterator i = list_class_stmt->begin() ; i != list_class_stmt->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListStmt(ListStmt *list_stmt)
{
  for (ListStmt::iterator i = list_stmt->begin() ; i != list_stmt->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListItem(ListItem *list_item)
{
  for (ListItem::iterator i = list_item->begin() ; i != list_item->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListType(ListType *list_type)
{
  for (ListType::iterator i = list_type->begin() ; i != list_type->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListExpr(ListExpr *list_expr)
{
  for (ListExpr::iterator i = list_expr->begin() ; i != list_expr->end() ; ++i)
  {
    (*i)->accept(this);
  }
}


void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}



