-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE CPP                  #-}
{-# LANGUAGE FlexibleInstances    #-}
{-# LANGUAGE LambdaCase           #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for PrintLattepp.

module Syntax.PrintLattepp where

import           Data.Char         (Char, isSpace)
import           Prelude           (Bool (..), Double, Int, Integer, ShowS,
                                    String, all, elem, foldr, id, map, null,
                                    replicate, showChar, showString, shows,
                                    span, ($), (*), (+), (++), (-), (.), (<),
                                    (==))
import qualified Syntax.AbsLattepp as AbsLattepp

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\'       -> showString "\\\\"
  '\n'       -> showString "\\n"
  '\t'       -> showString "\\t"
  s          -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsLattepp.Ident where
  prt _ (AbsLattepp.Ident i) = doc $ showString i
instance Print (AbsLattepp.Program' a) where
  prt i = \case
    AbsLattepp.Program _ topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print (AbsLattepp.TopDef' a) where
  prt i = \case
    AbsLattepp.FnDef _ type_ id_ args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])
    AbsLattepp.ClassDef _ id_ classblock -> prPrec i 0 (concatD [doc (showString "class"), prt 0 id_, prt 0 classblock])
    AbsLattepp.ExtClassDef _ id_1 id_2 classblock -> prPrec i 0 (concatD [doc (showString "class"), prt 0 id_1, doc (showString "extends"), prt 0 id_2, prt 0 classblock])

instance Print [AbsLattepp.TopDef' a] where
  prt _ []     = concatD []
  prt _ [x]    = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (AbsLattepp.Arg' a) where
  prt i = \case
    AbsLattepp.Arg _ type_ id_ -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_])

instance Print [AbsLattepp.Arg' a] where
  prt _ []     = concatD []
  prt _ [x]    = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (AbsLattepp.Block' a) where
  prt i = \case
    AbsLattepp.Block _ stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print (AbsLattepp.ClassBlock' a) where
  prt i = \case
    AbsLattepp.ClassBlock _ classstmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 classstmts, doc (showString "}")])

instance Print [AbsLattepp.ClassStmt' a] where
  prt _ []     = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsLattepp.Stmt' a] where
  prt _ []     = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (AbsLattepp.ClassStmt' a) where
  prt i = \case
    AbsLattepp.ClassEmpty _ -> prPrec i 0 (concatD [doc (showString ";")])
    AbsLattepp.ClassDecl _ type_ ids -> prPrec i 0 (concatD [prt 0 type_, prt 0 ids, doc (showString ";")])
    AbsLattepp.ClassMethod _ type_ id_ args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])

instance Print (AbsLattepp.Stmt' a) where
  prt i = \case
    AbsLattepp.Empty _ -> prPrec i 0 (concatD [doc (showString ";")])
    AbsLattepp.BStmt _ block -> prPrec i 0 (concatD [prt 0 block])
    AbsLattepp.Decl _ type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    AbsLattepp.Ass _ extident expr -> prPrec i 0 (concatD [prt 0 extident, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsLattepp.Incr _ extident -> prPrec i 0 (concatD [prt 0 extident, doc (showString "++"), doc (showString ";")])
    AbsLattepp.Decr _ extident -> prPrec i 0 (concatD [prt 0 extident, doc (showString "--"), doc (showString ";")])
    AbsLattepp.Ret _ expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AbsLattepp.VRet _ -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsLattepp.Cond _ expr stmt -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsLattepp.CondElse _ expr stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2])
    AbsLattepp.While _ expr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsLattepp.For _ type_ id_ extident stmt -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "("), prt 0 type_, prt 0 id_, doc (showString ":"), prt 0 extident, doc (showString ")"), prt 0 stmt])
    AbsLattepp.SExp _ expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])

instance Print (AbsLattepp.Item' a) where
  prt i = \case
    AbsLattepp.NoInit _ id_ -> prPrec i 0 (concatD [prt 0 id_])
    AbsLattepp.Init _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr])

instance Print [AbsLattepp.Item' a] where
  prt _ []     = concatD []
  prt _ [x]    = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsLattepp.Ident] where
  prt _ []     = concatD []
  prt _ [x]    = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (AbsLattepp.ExtIdent' a) where
  prt i = \case
    AbsLattepp.Id _ id_ -> prPrec i 0 (concatD [prt 0 id_])
    AbsLattepp.ArrId _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "["), prt 0 expr, doc (showString "]")])
    AbsLattepp.AttrId _ expr1 expr2 -> prPrec i 0 (concatD [prt 6 expr1, doc (showString "."), prt 6 expr2])

instance Print (AbsLattepp.PrimType' a) where
  prt i = \case
    AbsLattepp.Int _  -> prPrec i 0 (concatD [doc (showString "int")])
    AbsLattepp.Str _  -> prPrec i 0 (concatD [doc (showString "string")])
    AbsLattepp.Bool _ -> prPrec i 0 (concatD [doc (showString "boolean")])
    AbsLattepp.Void _ -> prPrec i 0 (concatD [doc (showString "void")])

instance Print (AbsLattepp.Type' a) where
  prt i = \case
    AbsLattepp.Primitive _ primtype -> prPrec i 0 (concatD [prt 0 primtype])
    AbsLattepp.ObjectType _ id_ -> prPrec i 0 (concatD [prt 0 id_])
    AbsLattepp.Array _ type_ -> prPrec i 0 (concatD [prt 0 type_, doc (showString "[]")])
    AbsLattepp.Fun _ type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")")])

instance Print [AbsLattepp.Type' a] where
  prt _ []     = concatD []
  prt _ [x]    = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (AbsLattepp.Expr' a) where
  prt i = \case
    AbsLattepp.ECast _ id_ expr -> prPrec i 7 (concatD [doc (showString "("), prt 0 id_, doc (showString ")"), prt 6 expr])
    AbsLattepp.ECastPrim _ primtype expr -> prPrec i 7 (concatD [doc (showString "("), prt 0 primtype, doc (showString ")"), prt 6 expr])
    AbsLattepp.ENewObject _ id_ -> prPrec i 6 (concatD [doc (showString "new"), prt 0 id_])
    AbsLattepp.ENewArr _ type_ expr -> prPrec i 6 (concatD [doc (showString "new"), prt 0 type_, doc (showString "["), prt 0 expr, doc (showString "]")])
    AbsLattepp.ENull _ -> prPrec i 6 (concatD [doc (showString "null")])
    AbsLattepp.EObject _ expr1 expr2 -> prPrec i 6 (concatD [prt 6 expr1, doc (showString "."), prt 6 expr2])
    AbsLattepp.EArr _ id_ expr -> prPrec i 6 (concatD [prt 0 id_, doc (showString "["), prt 0 expr, doc (showString "]")])
    AbsLattepp.EVar _ id_ -> prPrec i 6 (concatD [prt 0 id_])
    AbsLattepp.ELitInt _ n -> prPrec i 6 (concatD [prt 0 n])
    AbsLattepp.ELitTrue _ -> prPrec i 6 (concatD [doc (showString "true")])
    AbsLattepp.ELitFalse _ -> prPrec i 6 (concatD [doc (showString "false")])
    AbsLattepp.EApp _ id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsLattepp.EString _ str -> prPrec i 6 (concatD [printString str])
    AbsLattepp.Neg _ expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AbsLattepp.Not _ expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    AbsLattepp.EMul _ expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AbsLattepp.EAdd _ expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AbsLattepp.ERel _ expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    AbsLattepp.EAnd _ expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    AbsLattepp.EOr _ expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])

instance Print [AbsLattepp.Expr' a] where
  prt _ []     = concatD []
  prt _ [x]    = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (AbsLattepp.AddOp' a) where
  prt i = \case
    AbsLattepp.Plus _  -> prPrec i 0 (concatD [doc (showString "+")])
    AbsLattepp.Minus _ -> prPrec i 0 (concatD [doc (showString "-")])

instance Print (AbsLattepp.MulOp' a) where
  prt i = \case
    AbsLattepp.Times _ -> prPrec i 0 (concatD [doc (showString "*")])
    AbsLattepp.Div _   -> prPrec i 0 (concatD [doc (showString "/")])
    AbsLattepp.Mod _   -> prPrec i 0 (concatD [doc (showString "%")])

instance Print (AbsLattepp.RelOp' a) where
  prt i = \case
    AbsLattepp.LTH _ -> prPrec i 0 (concatD [doc (showString "<")])
    AbsLattepp.LE _  -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsLattepp.GTH _ -> prPrec i 0 (concatD [doc (showString ">")])
    AbsLattepp.GE _  -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsLattepp.EQU _ -> prPrec i 0 (concatD [doc (showString "==")])
    AbsLattepp.NE _  -> prPrec i 0 (concatD [doc (showString "!=")])
